package reporter

import (
	"fmt"
	"os"
	"strconv"
	"strings"
	"time"

	"github.com/Sla0ui/scanera/internal/models"
)

// GenerateMarkdown creates a Markdown report
func (r *Reporter) GenerateMarkdown(outputPath string) error {
	var b strings.Builder
	activeCount, inactiveCount := r.GetStats()
	findings := r.sortedFindings()

	b.WriteString("# Scanera Domain Analysis Report\n\n")
	b.WriteString("Report generated on: " + time.Now().Format("January 2, 2006 15:04:05") + "\n\n")

	b.WriteString("## Summary\n\n")
	b.WriteString("- Total domains scanned: " + strconv.Itoa(len(r.results)) + "\n")
	b.WriteString("- Active domains: " + strconv.Itoa(activeCount) + "\n")
	b.WriteString("- Inactive domains: " + strconv.Itoa(inactiveCount) + "\n")
	if len(findings) > 0 {
		counts := r.severityCounts()
		fmt.Fprintf(&b, "- Findings: %d (%d critical, %d high, %d medium, %d low, %d info)\n",
			len(findings),
			counts[models.SeverityCritical], counts[models.SeverityHigh],
			counts[models.SeverityMedium], counts[models.SeverityLow], counts[models.SeverityInfo])
	}
	b.WriteString("\n")

	if len(findings) > 0 {
		b.WriteString("## Findings\n\n")
		b.WriteString("| Severity | Title | Domain | Location |\n")
		b.WriteString("|----------|-------|--------|----------|\n")
		for _, f := range findings {
			writeRow(&b, string(f.Severity.Normalize()), f.Title, f.Domain, f.Location)
		}
		b.WriteString("\n")
	}

	b.WriteString("## Active Domains\n\n")
	b.WriteString("| Domain | Final URL | Status Code | Server | Technologies |\n")
	b.WriteString("|--------|-----------|-------------|--------|--------------|\n")
	for _, result := range r.results {
		if result.Active {
			writeRow(&b, result.Domain, result.FinalURL, strconv.Itoa(result.StatusCode),
				result.ServerInfo.Server, strings.Join(techList(result), ", "))
		}
	}

	b.WriteString("\n## Inactive Domains\n\n")
	b.WriteString("| Domain | Status Code | Error |\n")
	b.WriteString("|--------|-------------|-------|\n")
	for _, result := range r.results {
		if !result.Active {
			writeRow(&b, result.Domain, strconv.Itoa(result.StatusCode), errString(result))
		}
	}

	b.WriteString("\n---\n\n")
	b.WriteString("Generated by Scanera " + Version + "\n")

	if err := os.WriteFile(outputPath, []byte(b.String()), 0644); err != nil {
		return fmt.Errorf("failed to write Markdown file: %w", err)
	}
	return nil
}

func writeRow(b *strings.Builder, cells ...string) {
	b.WriteString("|")
	for _, c := range cells {
		b.WriteString(" " + mdCell(c) + " |")
	}
	b.WriteString("\n")
}

// mdCell keeps a value inside its table cell: a raw pipe would start a new
// column and a newline would end the row.
// mdEscaper backslash-escapes characters that would let server-controlled text
// (titles, headers, errors) turn into links, images, code or raw HTML.
var mdEscaper = strings.NewReplacer(
	`\`, `\\`, "|", `\|`, "`", "\\`", "[", `\[`, "]", `\]`,
	"<", "&lt;", ">", "&gt;", "*", `\*`, "_", `\_`, "!", `\!`,
)

func mdCell(s string) string {
	return mdEscaper.Replace(oneLine(s))
}
