run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - goconst
    - unparam
    - unconvert
    - dupl
    - prealloc
    - exportloopref
    - nilerr
    - nolintlint
    - revive
    - gosec

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    check-shadowing: true
    enable-all: true

  gofmt:
    simplify: true

  gosec:
    excludes:
      - G402 # TLS InsecureSkipVerify controlled by config
      - G114 # Use of net/http serve function without timeout

  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - dupl
        - gosec

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
